website/TiberSolutions/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
import dashboard.urls
import dashboard.views as dash_views

urlpatterns = [
    url(r'^$', dash_views.home),
    url(r'^dashboard/', include(dashboard.urls))
]

website/dashboard/urls.py
from django.conf.urls import include, url
from dashboard import views as dash_views

app_name = 'dashboard'

urlpatterns = [
    url(r'^$', dash_views.index, name='index'),
    url(r'patient/', dash_views.home, name='dashhome'),

]

website/dashboard/models.py
from django.db import models

# Create your models here.

website/dashboard/views.py
from django.shortcuts import render
from pyathena import connect
import os
import numpy as np
from dashboard.ConnectSagemaker import invoke_sagemake_endpoint
from decimal import getcontext, Decimal

unique_countries = []
unique_conditions = []
unique_interventions = []
cursor = connect(aws_access_key_id=os.environ["accessKey"],
                 aws_secret_access_key=os.environ["secretKey"],
                 s3_staging_dir='s3://aws-athena-query-results-565635975808-us-east-2/',
                 region_name='us-east-2').cursor()


def index(request):
    return render(request, 'dashboard/index.html')


def readAccessKey():
    return 0


def readSecretKey():
    return 0


# reported event:
# table: browse_condition(healthy), eligibilities(gender), countries(country), age(optional),


def getColumnName(tablename):
    query = "select column_name from information_schema.columns where table_name = " + "'" + tablename + "'"
    cursor = connect(aws_access_key_id=os.environ["accessKey"],
                     aws_secret_access_key=os.environ["secretKey"],
                     s3_staging_dir='s3://aws-athena-query-results-565635975808-us-east-2/',
                     region_name='us-east-2').cursor()
    cursor.execute(query)
    columnName = []
    for row in cursor:
        line = str(row)
        print(line)
        start = line.index("'", 0, len(line))
        end = line.index("'", start + 1, len(line))
        columnName.append(line[start + 1: end])
    print(columnName)
    return columnName


# Create your views here.

def home(request):
    global unique_countries, unique_conditions, unique_interventions, cursor
    if len(unique_countries) == 0:
        unique_conditions = np.load('dashboard/templates/npy/conditions_catagories.npy')
        unique_countries = np.load('dashboard/templates/npy/countries_catagories.npy')
        unique_interventions = np.load('dashboard/templates/npy/interventions_catagories.npy')
    if request.method == "GET":
        return render(request, 'dashboard/patient-home.html',
                      {"show": False, "conditions": unique_conditions, "countries": unique_countries,
                       "interventions": unique_interventions})
    if request.method == 'POST':
        # cursor = connect(aws_access_key_id=os.environ["accessKey"],
        #                  aws_secret_access_key=os.environ["secretKey"],
        #                  s3_staging_dir='s3://aws-athena-query-results-565635975808-us-east-2/',
        #                  region_name='us-east-2').cursor()

        # if 'tablename' in request.POST:
        #     tablename = request.POST['tablename']
        #     columnNames = getColumnName(tablename)
        #     attributeLine = []
        #     for column in columnNames:
        #         query = "select " + column + " from clinic." + tablename + " limit 10"
        #         print(query)
        #         cursor.execute(query)
        #         attributes = []
        #         for row in cursor:
        #             line = str(row)
        #             start = -1
        #             end = len(line)
        #             if line.find("'") != -1:
        #                 start = line.index("'", 0, len(line))
        #                 end = line.index("'", start + 1, len(line))
        #             attributes.append(line[start + 1: end])
        #         attributeLine.append(attributes)
        #     a = map(list, zip(*attributeLine))
        #     context = {"tablename": tablename, "columnNames": columnNames, "attributeLine": a, "show": True}
        #     return render(request, 'dashboard/patient-home.html', context)
        # else:
        condition = request.POST.getlist('health_condition[]')
        gender = request.POST['gender']
        country = request.POST['country']
        intervention = request.POST.getlist('interventions[]')
        facility_num = request.POST['facility_num']
        us_facility = request.POST['us_facility']
        sponsor_num = request.POST['sponsor_num']
        vector = []
        vector.append(int(facility_num))
        if us_facility == 'yes':
            vector.append(1)
        else:
            vector.append(0)
        vector.append(int(sponsor_num))
        vector.append(condition)
        vector.append(intervention)
        vector.append(country)
        print(vector)
        # build condition list
        conditionlist = "("
        for c in condition:
            conditionlist += '\''
            conditionlist += c
            conditionlist += '\''
            conditionlist += ","
        # get rid of the last ,
        conditionlist = conditionlist[0: len(conditionlist) - 1]
        conditionlist += ')'

        print("HERE COMES THE EAD!!!!!!")
        print(conditionlist)
        query = "select s.nct_id, brief_title, array_agg(distinct adverse_event_term) adverse_event" \
                + " from clinic.studies s" \
                + " join clinic.reported_events r" \
                + " on s.nct_id = r.nct_id" \
                + " join" \
                + " (" \
                + " select nct_id" \
                + "	from clinic.countries" \
                + "	where name = '" + country + "'" \
                + " ) c" \
                + " on s.nct_id = c.nct_id" \
                + " join" \
                + " (" \
                + " select nct_id" \
                + " 	from clinic.browse_conditions" \
                + " 	where downcase_mesh_term in " + conditionlist \
                + " ) bc" \
                + " on s.nct_id = bc.nct_id" \
                + " join" \
                + " (" \
                + "	select nct_id" \
                + " 	from clinic.eligibilities" \
                + " 	where gender = '" + gender + "'" \
                + " ) e" \
                + " on s.nct_id = e.nct_id" \
                + " group by s.nct_id, brief_title" \
                + " limit 10;"
        print(query)
        cursor.execute(query)
        columnNames = ['nct_id', 'brief_title', 'adverse_events']
        attributeLine = []
        for row in cursor:
            attributes = []
            attributes.append(row[0])
            attributes.append(row[1])
            attributes.append(row[2])
            attributeLine.append(attributes)

        endpoint_name = 'yangz5test'
        percentage = invoke_sagemake_endpoint(vector, endpoint_name) * 100
        print(percentage)
        percentage = Decimal(percentage).quantize(Decimal('0.00'))

        context = {"tablename": 'result table', "columnNames": columnNames, "attributeLine": attributeLine,
                   "show": True, "percentage": percentage, "conditions": unique_conditions,
                   "countries": unique_countries, "interventions": unique_interventions}
        return render(request, 'dashboard/patient-home.html', context)

website/dashboard/templates/dashboard/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/style.css' %}">

    <!-- JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    {#    <script type="text/javascript" src="{% static 'dashboard/js/script.js' %}"></script>#}

    <!-- Icon -->
    {#    <link rel="icon" type="image/png" href="{% static 'dashboard/icon.png' %}"/>#}

    <title>ACCT</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
</nav>
<div class="w-75 mx-auto">
    {% block body %}
    {% endblock %}
</div>
<div class = "table">
    {% block t %}
    {% endblock %}
</div>

<div class = "empty">
    <p>
    <br><br><br><br>
        <br><br><br><br>
    </p>
    <p>

    </p>
</div>
<div class="footer">
    <p>
        <a class="badge badge-secondary" href="#">About</a> &nbsp;&nbsp;
        <a class="badge badge-secondary" href="https://github.com/huyingfan420/TiberSolutions"><i
                class="fa fa-github"></i></a>
    </p>
</div>
</body>
</html>

website/dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block body %}
    <div class="usercase row align-items-center">
        <div class="col text-center">
            <a href="{% url 'dashboard:dashhome' %}">
                <img src="{% static 'dashboard/images/patient.png' %}" class="rounded" alt="Patient" border="5">
            </a>
        </div>
        <div class="col text-center">
            <img src="{% static 'dashboard/images/institute.png' %}" class="rounded" alt="Institute">
        </div>
        <div class="col text-center">
            <img src="{% static 'dashboard/images/sponsor.png' %}" class="rounded" alt="Sponsor">
        </div>
    </div>
{% endblock %}

website/dashboard/templates/dashboard/patient-home.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block body %}
    <form class="mt-4" method="post" action="{% url 'dashboard:dashhome' %}">
        <span>Personal Information</span>
        <hr>
        <div class="form-row">
            <div class="col-md-6 mb-3">
                <label for="validationTooltip01">First name</label>
                <input type="text" class="form-control" id="validationTooltip01" placeholder="First name" required>
            </div>
            <div class="col-md-6 mb-3">
                <label for="validationTooltip02">Last name</label>
                <input type="text" class="form-control" id="validationTooltip02" placeholder="Last name" required>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-6 mb-3">
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Gender</label>
                    <select class="form-control" id="exampleFormControlSelect1" name="gender">
                        <option>Male</option>
                        <option>Female</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <label for="validationTooltip04">Birth Date</label>
                <input type="text" class="form-control" id="validationTooltip04" placeholder="MM / DD / YYYY" required>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-12">
                <label for="exampleFormControlSelect1">Health Condition</label>
                <select class="form-control" id="exampleFormControlSelectCondition" name="health_condition[]"
                        multiple="multiple">
                    {% for condition in conditions %}
                        <option>{{ condition }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-3 mb-3">
                <label for="validationTooltip07">City</label>
                <input type="text" class="form-control" id="validationTooltip07" placeholder="City" required>
                <div class="invalid-tooltip">
                    Please provide a valid city.
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <label for="validationTooltip08">State</label>
                <input type="text" class="form-control" id="validationTooltip08" placeholder="State" required>
                <div class="invalid-tooltip">
                    Please provide a valid state.
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Country</label>
                    <select class="form-control" id="exampleFormControlSelectCountry" name="country">
                        {% for country in countries %}
                            <option>{{ country }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <label for="validationTooltip05">Zip</label>
                <input type="text" class="form-control" id="validationTooltip05" placeholder="Zip" required>
                <div class="invalid-tooltip">
                    Please provide a valid zip.
                </div>
            </div>
        </div>
        <div class="form-row mb-4">
            <div class="form-group col-md-6">
                <label for="inputEmail4">Email</label>
                <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
            </div>
        </div>

        <span>Clinical Trial Information</span>
        <hr>
        <div class="form-row">
            <div class="form-group col-md-12">
                <label for="exampleFormControlSelect1">Treatment</label>
                <select class="form-control" id="exampleFormControlSelectIntervention" name="interventions[]"
                        multiple="multiple">
                    {% for intervention in interventions %}
                        <option>{{ intervention }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Number of Sponsors</label>
                <input type="text" class="form-control" id="validationTooltip01" placeholder="Number of Sponsors"
                       name="sponsor_num"
                       required>
            </div>
            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Contain U.S. Facilities</label>
                <select class="form-control" id="exampleFormControlSelect1" name="us_facility">
                    <option>yes</option>
                    <option>no</option>
                </select>
            </div>
            <div class="col-md-4 mb-3">
                <label for="validationTooltip02">Number of Facilities</label>
                <input type="text" class="form-control" id="validationTooltip02" placeholder="Number of Facilities"
                       name="facility_num"
                       required>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
        {% csrf_token %}
    </form>

    {#    <form method="POST" action="{% url 'dashboard:dashhome' %}">#}
    {#        <select name="tablename">#}
    {#            <option value="reported_events">reported_events</option>#}
    {#            <option value="browse_conditions">browse_conditions</option>#}
    {#            <option value="browse_interventions">browse_interventions</option>#}
    {#        </select>#}
    {#        <button value="submit">submit</button>#}
    {#        {% csrf_token %}#}
    {#    </form>#}

    <br><br><br>
    {% if show %}
        <p>Based on personal and clinical trial information, the probability of encountering any adverse events is: {{ percentage }}%</p>
        <progress max="100" value="{{ percentage }}" class="html5">
            <div class="progress-bar">
                <span style="width: 100%">100%</span>
            </div>
        </progress>
        {% if attributeLine %}
            <p>Based on personal information, we recommend some clinical trials similar to your condition, and highlight
                all possible adverse events you might suffer.</p>
            <table border="1" id="results">
                <tr>
                    {% for columnname in columnNames %}
                        <th>  {{ columnname }}</th>
                    {% endfor %}
                </tr>
                {% for attributes in attributeLine %}
                    <tr>
                        {% for row in attributes %}
                            <td>  {{ row }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}

            </table>
        {% else %}
            <p>There is no related clinical trial based on the information you provide.</p>
        {% endif %}
    {% endif %}
    <script src="../../static/js/dropdown.js" type="text/javascript"></script>
{% endblock %}